### ISSUE TITLE
`!!python/tuple` is being written to the YAML file

### ISSUE THREAD

**Issue by PSNAppz** [CN-UPB/B-JointSP#28]
When oversubscription happens `!!python/tuple` is being written to the YAML file.

This causes an error being thrown when parsing the YAML file.

```
  dr_oversub:
  - link: !!python/tuple
    - pop0
    - pop2
```

**Comment by stefanbschneider** [comment]
I usually tested cases without link over-subscription, so may easily be that I never noticed this issue.

The problem should be here, where the oversubscribed link is written to yaml: https://github.com/CN-UPB/B-JointSP/blob/master/src/bjointsp/read_write/writer.py#L149

```python
result["placement"]["dr_oversub"].append({"link": l})
```

I think appending `{"link": list(l)}` instead of `{"link": l}` may solve the problem. Could you please test it and if it does solve the problem make a pull request?

**Comment by PSNAppz** [comment]
appending `{"link": list(l)}` instead of `{"link": l}` solved the problem. I'll make a PR soon.
